# Generated by Django 4.2.6 on 2023-10-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_customuser_department_customuser_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department_access',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='map.department'),
        ),
    ]
