# Generated by Django 4.2.6 on 2023-10-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_sensortype_sensor_location_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='main_employ',
            field=models.CharField(default='Иванов Иван Иванович', max_length=200),
            preserve_default=False,
        ),
    ]
