# Generated by Django 4.1 on 2023-11-08 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0008_maprooms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MapRooms",
        ),
    ]
