# Generated by Django 4.1 on 2023-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0010_maprooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="maprooms",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
