# Generated by Django 4.1 on 2023-11-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0011_maprooms_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapIcons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map.mapicons",
                    ),
                ),
            ],
        ),
    ]
