# Generated by Django 4.1 on 2023-11-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0012_mapicons_mappoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappoint",
            name="coordinates_json",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mappoint",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
