# Generated by Django 4.1 on 2023-11-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0013_mappoint_coordinates_json_mappoint_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappoint",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
