# Generated by Django 4.1 on 2023-11-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0014_alter_mappoint_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maprooms",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
