# Generated by Django 4.1 on 2023-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0016_alter_maprooms_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maprooms",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
